// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module prim_secded_36_29_enc (
  input        [28:0] data_i,
  output logic [35:0] data_o
);

  always_comb begin : p_encode
    data_o = 36'(data_i);
    data_o[29] = ^(data_o & 36'h00606BD25);
    data_o[30] = ^(data_o & 36'h01EBA8050);
    data_o[31] = ^(data_o & 36'h0013D89AA);
    data_o[32] = ^(data_o & 36'h011234ED1);
    data_o[33] = ^(data_o & 36'h002C1323B);
    data_o[34] = ^(data_o & 36'h00DCC624C);
    data_o[35] = ^(data_o & 36'h018505586);
  end

endmodule : prim_secded_36_29_enc
