// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// SECDED encoder generated by util/design/secded_gen.py

module prim_secded_55_48_enc (
  input        [47:0] data_i,
  output logic [54:0] data_o
);

  always_comb begin : p_encode
    data_o = 55'(data_i);
    data_o[48] = ^(data_o & 55'h00EEC800007FFF);
    data_o[49] = ^(data_o & 55'h00F35801FF801F);
    data_o[50] = ^(data_o & 55'h003FE87E0781E1);
    data_o[51] = ^(data_o & 55'h00F5B38E388E22);
    data_o[52] = ^(data_o & 55'h004FBDB2C93244);
    data_o[53] = ^(data_o & 55'h00FE76D5525488);
    data_o[54] = ^(data_o & 55'h0099FF69A46910);
  end

endmodule : prim_secded_55_48_enc
